## load logistic and lorenz logs

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook

In [ ]:
fig = plt.figure(figsize=(20,3.5))
ax = plt.gca()

def plot_ts(pred):
    y_true, y_pred =pred
    ax = fig.add_subplot(1, 4, i+1)
    ax.plot(y_true[:100,seq_id],'g')
    ax.set_ylim([-20,20])
    ax = fig.add_subplot(2, 4, i+1)
    ax.plot(y_pred[:100,seq_id], 'r')
    ax.set_ylim([-20,20])
    ax.set_title(model)

### load logs for lorenz and print test error

In [26]:
time_stamp ="05-17-17-16-17-44"
exp='lorenz'
models =["basic_rnn","basic_lstm","matrix_rnn","tensor_rnn"]
hz_list= [32, 64, 128, 256]
lr_list =[1,2,3,4]


import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt



def read_config(fstream):
    d = {}
    for line in fstream:
        line.rstrip()
        tokens = line.split('\t')
        for token in tokens:
            try:
                key, val = token.split(":")
                d[key] = float(val)                
            except ValueError:
                'error prop'
    return d

def load_log(hz, lr, model):
    data_path = "/var/tmp/tensorRNN/log/"+exp+"/"+time_stamp+"/hz_"+str(hz)+"/"+"lr_1e-"+str(lr)+"/"+model+"/"
    f_pred= "predict.npy"
    f_err = "config_error.out"
    pred =  np.load(data_path+f_pred )
    with open(data_path+"/"+f_err,'r') as fstream:
        config = read_config(fstream)
    return config, pred

errs = np.ndarray((len(hz_list), len(lr_list), len(models)))
i=0
for hz in hz_list:
    j=0
    for lr in lr_list:
        k=0
        for model in models:
            print('load model {:s}, hidden size {:d}, learning rate 1e-{:d}'.format(model, hz, lr))
            config, pred = load_log(hz, lr, model)
            print('train error:',config['train_error'],'valid error:',config['valid_error'],'test err:',config['test_error'])
            errs[i,j,k] =  config['test_error']
            k +=1
        j+=1
    i+=1

load model basic_rnn, hidden size 32, learning rate 1e-1
train error: 0.199724409168 valid error: 0.22919777389 test err: 0.212335811075
load model basic_lstm, hidden size 32, learning rate 1e-1
train error: 0.103897959851 valid error: 0.107461961939 test err: 0.115497416101
load model matrix_rnn, hidden size 32, learning rate 1e-1
train error: 0.110847434811 valid error: 0.11202717785 test err: 0.109184120396
load model tensor_rnn, hidden size 32, learning rate 1e-1
train error: 0.128857591144 valid error: 0.114510083469 test err: 0.114671018826
load model basic_rnn, hidden size 32, learning rate 1e-2
train error: 0.156886276448 valid error: 0.158386818475 test err: 0.151554558006
load model basic_lstm, hidden size 32, learning rate 1e-2
train error: 0.0327709592114 valid error: 0.035424635658 test err: 0.0350934138734
load model matrix_rnn, hidden size 32, learning rate 1e-2
train error: 0.0920729562752 valid error: 0.0962623985331 test err: 0.101214215459
load model tensor_rnn, hidd

In [27]:
for k in range(len(models)):
    print(np.min(errs[:,:,k], axis = 1)) #row min--hidden size

[ 0.14485706  0.15129987  0.14699492  0.14901385]
[ 0.03509341  0.02917815  0.04957961  0.0670161 ]
[ 0.10121422  0.10036506  0.10376984  0.10785991]
[ 0.01029905  0.01447066  0.00989716  0.00853924]
